project:
  type: website
  output-dir: docs

website:
  title: "HumGenome25"
  navbar:
    left:
      - text: "Home"
        href: index.qmd
      - text: "Lab 7"
        href: Lab7.html

format:
  html:
    toc: true
    toc_float: true
    embed-resources: true

execute:
  warning: false
  message: false
