name: Quarto Publish

on:
  push:
    branches: [main]

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
      - uses: quarto-dev/quarto-actions/setup@v2

      # 游릭 install R
      - name: Setup R
        uses: r-lib/actions/setup-r@v2

      # 游릭 install needed R packages
      - name: Install R packages
        run: |
          Rscript -e 'install.packages(c("knitr","rmarkdown"), repos="https://cloud.r-project.org")'

      # 游릭 render Quarto website
      - name: Render site
        run: quarto render

      # 游릭 publish to GitHub Pages
      - name: Publish to GitHub Pages
        uses: quarto-dev/quarto-actions/publish@v2
        with:
          target: gh-pages
